[project]
dependencies = [
    'semver >= 2.13.0',
    'json5 >= 0.9.6',
    'pathspec >= 0.9.0'
]

[build-system]
requires = [
    'setuptools>=42',
    'wheel'
]
build-backend = 'setuptools.build_meta'
